version: '3.8'

services:
  db:
    image: postgres:16
    container_name: project_db
    environment:
      POSTGRES_DB: project_db
      POSTGRES_USER: project_user
      POSTGRES_PASSWORD: project_password
    ports:
      - "5432:5432"

  app:
    build: .
    container_name: project_api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/project_db
      SPRING_DATASOURCE_USERNAME: project_user
      SPRING_DATASOURCE_PASSWORD: project_password
    ports:
      - "8080:8080"
    depends_on:
      - db
