server:
  port: 8080

spring:

  web:
    resources:
      add-mappings: true
      static-locations: classpath:/static/

  datasource:
    url: jdbc:postgresql://localhost:5432/project_db
    username: project_username
    password: project_password
    driverClassName: org.postgresql.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    open-in-view: false

  liquibase:
    enabled: true
    drop-first: true
    change-log: classpath:db/changelog/database-changelog.xml

logging:
  level:
    ru.social.network.impl.service: DEBUG
    jakarta.mail: DEBUG


access-token:
  private: "access-refresh-token-keys/access-token-private.key"
  public: "access-refresh-token-keys/access-token-public.key"
refresh-token:
  private: "access-refresh-token-keys/refresh-token-private.key"
  public: "access-refresh-token-keys/refresh-token-public.key"
